kind = "mobile"
previewPath = "/"
title = "Sagan Tracker"
version = "1.0.0"
id = "artifacts/sagan-tracker"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18689

[services.development]
run = "pnpm --filter @workspace/sagan-tracker run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sagan-tracker", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/sagan-tracker", "run", "serve" ]

[services.env]
PORT = "18689"
BASE_PATH = "/"
