const colors = {
  light: {
    text: "#18181B",
    tint: "#2563EB",
    background: "#FAFAFA",
    foreground: "#18181B",
    card: "#FFFFFF",
    cardForeground: "#18181B",
    primary: "#18181B",
    primaryForeground: "#FFFFFF",
    secondary: "#F4F4F5",
    secondaryForeground: "#3F3F46",
    muted: "#F4F4F5",
    mutedForeground: "#71717A",
    accent: "#2563EB",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E4E4E7",
    input: "#E4E4E7",
    received: "#2563EB",
    receivedBg: "#EFF6FF",
    given: "#7C3AED",
    givenBg: "#F5F3FF",
    negative: "#DC2626",
    positiveBg: "#EFF6FF",
    negativeBg: "#FEF2F2",
  },
  radius: 12,
};

export default colors;
